version: '2'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
    recountmethylation:
        build: .
        container_name: "recountmethylation"
        image: metamaden/recountmethylation_docker
        environment:
            - NODE_ENV=development
        volumes:
            - .:/var/www:rw
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        ports:
            - 3000:3000
            - 9000:9000
        links:
            - mongodb
        depends_on:
            - mongodb